// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjetmszvdcznnomobznw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqZXRtc3p2ZGN6bm5vbW9iem53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjkxNTYsImV4cCI6MjA2NzkwNTE1Nn0.S-kGKtfpPg4Ci6BOI2GmVwrtC2yc4bBBcrTHa5xNCRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});